# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('index', '0002_auto_20190221_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
