"""empty message

Revision ID: 49ac22a9bfaa
Revises: 
Create Date: 2019-01-28 21:08:44.285412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49ac22a9bfaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tname', sa.String(length=30), nullable=False),
                    sa.Column('tage', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=80), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('isActive', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wife',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('wname', sa.String(length=30), nullable=False),
                    sa.Column('wage', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('teacer')
    op.drop_index('email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
                    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
                    sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('teacer',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('tname', mysql.VARCHAR(length=30), nullable=False),
                    sa.Column('tage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('wife')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('teacher')
    # ### end Alembic commands ###
