"""empty message

Revision ID: 32699e8120ac
Revises: e8f3e8c1481a
Create Date: 2019-01-31 20:42:42.824311

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '32699e8120ac'
down_revision = 'e8f3e8c1481a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_teacher',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_teacher')
    # ### end Alembic commands ###
