"""empty message

Revision ID: 6995d57212e5
Revises: 
Create Date: 2019-01-28 21:29:09.079182

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6995d57212e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(length=200), nullable=True),
                    sa.Column('url', sa.String(length=200), nullable=True),
                    sa.Column('upwd', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
