"""empty message

Revision ID: 3927d81c8484
Revises: 8309d65b635d
Create Date: 2019-02-12 10:58:14.411960

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3927d81c8484'
down_revision = '8309d65b635d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=80), nullable=True),
                    sa.Column('password', sa.String(length=100), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('isActive', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('password')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
