"""empty message

Revision ID: 8f52aef9e8bd
Revises: 3927d81c8484
Create Date: 2019-02-12 11:23:37.897443

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f52aef9e8bd'
down_revision = '3927d81c8484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
