"""empty message

Revision ID: d9f9eaddd6c1
Revises: 8f52aef9e8bd
Create Date: 2019-02-12 11:24:35.107684

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd9f9eaddd6c1'
down_revision = '8f52aef9e8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'users', ['password'], unique=True)
    # ### end Alembic commands ###
