"""empty message

Revision ID: 1bbae3eb4eba
Revises: 
Create Date: 2019-01-30 14:50:53.683440

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1bbae3eb4eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'course_id')
    # ### end Alembic commands ###
