"""empty message

Revision ID: f102f800f22f
Revises: 
Create Date: 2019-02-13 18:46:53.456532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f102f800f22f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pname', sa.String(length=80), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('citys',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cname', sa.String(length=80), nullable=True),
                    sa.Column('pid', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['pid'], ['provinces.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('uname', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('uname', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('upwd', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('uemail', mysql.VARCHAR(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_index('uname', 'user', ['uname'], unique=True)
    op.create_table('users',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=80), nullable=True),
                    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
                    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
                    sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_table('citys')
    op.drop_table('provinces')
    # ### end Alembic commands ###
